# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump version')"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Install jq to parse version
        run: sudo apt install -y jq make
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8
      
      - name: Install bumpversion to increment version number
        run: pip install bump2version
      
      - name: Configure Git
        run: |
          git config --global user.name "Sylvan Le Deunff"
          git config --global user.email "sledeunf@gmail.com"
      
      - name: Bump version and push it on master branch
        run: make bump
